/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import graphs.Graph;
import helpers.TaskManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import operations.FileExporter;
import operations.FileImporter;
import operations.GraphAlgorithms;
import operations.GraphManager;
import operations.GraphOperations;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    private GraphOperations graphOps;
    private static GraphManager graphManager;
    private GraphAlgorithms GraphAlg;

    /**
     * Creates new form Main
     */
    public MainFrame() {
        this.graphManager = new GraphManager(graphCount);
        this.graphOps = new GraphOperations();
        this.GraphAlg = new GraphAlgorithms();
        initComponents();
        graphList.setModel(graphManager.getListModel());
        updateGraphListUI();
        setupListSelectionListener();
        setupTaskManager();
    }

    private void setupTaskManager() {
        TaskManager manager = new TaskManager();
        GraphAlgorithms.setTaskManager(manager);
    }

    // Field to hold the list model
    private void setupListSelectionListener() {
        graphList.addListSelectionListener(this::graphListValueChanged);
    }

    private void updateGraphListUI() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Graph graph : graphManager.getGraphs()) {
            model.addElement(graph.getName());
        }
        graphList.setModel(model);
        graphCount.setText("" + model.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        graphCount = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        graphList = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        createGraphButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        deleteGraphButton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        exportGraphButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        fsApsButton = new javax.swing.JButton();
        fpAppButton = new javax.swing.JButton();
        adjMatrixButton = new javax.swing.JButton();
        ddiButton = new javax.swing.JButton();
        ddeButton = new javax.swing.JButton();
        weightMatButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberOfVerticesLabel = new javax.swing.JLabel();
        numberOfEdgesLabel = new javax.swing.JLabel();
        graphTypeLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        distanceAlg = new javax.swing.JMenuItem();
        rankAlg = new javax.swing.JMenuItem();
        tarjanAlg = new javax.swing.JMenuItem();
        dijkstraAlg = new javax.swing.JMenuItem();
        danzigAlg = new javax.swing.JMenuItem();
        pruferAlg = new javax.swing.JMenuItem();
        scheduleManagerAlg = new javax.swing.JMenuItem();
        kruskalAlg = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        aboutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 293));

        jLabel4.setText("Nombre de Graphs :");

        graphCount.setText("NaN");

        jPanel5.setBackground(new java.awt.Color(221, 221, 221));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("GraphList"));

        graphList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item1", "item2", "item3", "item4", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        graphList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                graphListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(graphList);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(221, 221, 221));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "operations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        createGraphButton.setText("create");
        createGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performCreateGraph(evt);
            }
        });

        jButton7.setText("Edit");

        deleteGraphButton.setText("Delete");
        deleteGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performDeleteGraph(evt);
            }
        });

        jButton9.setText("create (I)");

        importButton.setText("import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        exportGraphButton.setText("export");
        exportGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performExportGraph(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(createGraphButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(12, 12, 12)
                        .addComponent(deleteGraphButton))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(12, 12, 12)
                        .addComponent(importButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exportGraphButton)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createGraphButton)
                    .addComponent(jButton7)
                    .addComponent(deleteGraphButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(importButton)
                    .addComponent(exportGraphButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graphCount, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(graphCount))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph Structures"));

        fsApsButton.setText("FS_APS");
        fsApsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFsApsAction(evt);
            }
        });

        fpAppButton.setText("FP_APP");
        fpAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFpApp(evt);
            }
        });

        adjMatrixButton.setText("MAT_ADJ");
        adjMatrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAdjMatrix(evt);
            }
        });

        ddiButton.setText("DDI");
        ddiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDDI(evt);
            }
        });

        ddeButton.setText("DDE");
        ddeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDDE(evt);
            }
        });

        weightMatButton.setText("MAT_POIDS");
        weightMatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showWeightMat(evt);
            }
        });

        jButton2.setText("AFFICHER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weightMatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fsApsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ddiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fpAppButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adjMatrixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ddeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fsApsButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fpAppButton)
                        .addComponent(adjMatrixButton)))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddiButton)
                    .addComponent(ddeButton)
                    .addComponent(weightMatButton))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph info"));
        jPanel4.setToolTipText("");

        jLabel1.setText("Nombre de Sommets :");

        jLabel2.setText("Nombre d'arrêtes :");

        jLabel3.setText("Type de Graph :");

        numberOfVerticesLabel.setText("NaN");

        numberOfEdgesLabel.setText("NaN");

        graphTypeLabel.setText("NaN");

        jLabel5.setText("Weighted : ");

        weightLabel.setText("NaN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfVerticesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfEdgesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(graphTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberOfVerticesLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberOfEdgesLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(graphTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(weightLabel))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Algorithms");

        distanceAlg.setText("Distance");
        distanceAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performDistanceAlg(evt);
            }
        });
        jMenu3.add(distanceAlg);

        rankAlg.setText("Rank");
        rankAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performRankAlg(evt);
            }
        });
        jMenu3.add(rankAlg);

        tarjanAlg.setText("Tarjan");
        tarjanAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performTarjanAlg(evt);
            }
        });
        jMenu3.add(tarjanAlg);

        dijkstraAlg.setText("Dijkstra");
        dijkstraAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performDijkstraAlg(evt);
            }
        });
        jMenu3.add(dijkstraAlg);

        danzigAlg.setText("Danzig");
        danzigAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performDanzigAlg(evt);
            }
        });
        jMenu3.add(danzigAlg);

        pruferAlg.setText("Prufer");
        pruferAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performPruferAlg(evt);
            }
        });
        jMenu3.add(pruferAlg);

        scheduleManagerAlg.setText("Schedule Manager");
        scheduleManagerAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performScheduleManagerAlg(evt);
            }
        });
        jMenu3.add(scheduleManagerAlg);

        kruskalAlg.setText("Kruskal");
        kruskalAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performKruskalAlg(evt);
            }
        });
        jMenu3.add(kruskalAlg);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Example");
        jMenuBar1.add(jMenu5);

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performShowAbout(evt);
            }
        });
        jMenuBar1.add(aboutButton);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showFsApsAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showFsApsAction
        graphOps.performFsApsOperation();
    }//GEN-LAST:event_showFsApsAction

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        try {
            String jsonContent = FileImporter.selectJsonFile();
            if (jsonContent != null) {
                Graph newGraph = FileImporter.importJsonFile(jsonContent);
                if (newGraph != null) {
                    graphManager.addGraph(newGraph);  // Assuming you have a GraphManager instance
                    updateGraphListUI();
                    System.out.println("Graph added: " + newGraph.getName());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Failed to import graph: " + ex.getMessage(), "Import Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_importButtonActionPerformed

    private void graphListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_graphListValueChanged
        if (!evt.getValueIsAdjusting()) {
            String selectedGraphName = graphList.getSelectedValue();
            Graph selectedGraph = graphManager.getGraph(selectedGraphName); // Assuming you have a method to fetch Graph

            if (selectedGraph != null) {
                updateGraphListUI();
                graphOps.setCurrentGraph(selectedGraph);
                GraphAlg.setCurrentGraph(selectedGraph);
            }
        }
    }//GEN-LAST:event_graphListValueChanged

    private void showFpApp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showFpApp
        graphOps.performFpAppOperation();
    }//GEN-LAST:event_showFpApp

    private void showAdjMatrix(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAdjMatrix
        graphOps.performAdjMatrixOperation();
    }//GEN-LAST:event_showAdjMatrix

    private void showDDI(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDDI
        graphOps.performDDIOperation();
    }//GEN-LAST:event_showDDI

    private void showDDE(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDDE
        graphOps.performDDEOperation();
    }//GEN-LAST:event_showDDE

    private void showWeightMat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showWeightMat
        graphOps.performWeightMatrixOperation();
    }//GEN-LAST:event_showWeightMat

    private void performDistanceAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performDistanceAlg
        GraphAlg.performDistanceAlg();
    }//GEN-LAST:event_performDistanceAlg

    private void performRankAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performRankAlg
        GraphAlg.performRankAlg();
    }//GEN-LAST:event_performRankAlg

    private void performTarjanAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performTarjanAlg
        GraphAlg.performTarjanAlg();
    }//GEN-LAST:event_performTarjanAlg

    private void performDijkstraAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performDijkstraAlg
        GraphAlg.performDijkstraAlg();
    }//GEN-LAST:event_performDijkstraAlg

    private void performDanzigAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performDanzigAlg
        GraphAlg.performDanzigAlg();
    }//GEN-LAST:event_performDanzigAlg

    private void performPruferAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performPruferAlg
        GraphAlg.performPruferAlg();
    }//GEN-LAST:event_performPruferAlg

    private void performScheduleManagerAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performScheduleManagerAlg
        GraphAlg.performScheduleManagerAlg();
    }//GEN-LAST:event_performScheduleManagerAlg

    private void performKruskalAlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performKruskalAlg
        // TODO add your handling code here:
        GraphAlg.performKruskalAlg();
    }//GEN-LAST:event_performKruskalAlg

    private void performExportGraph(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performExportGraph
        // TODO add your handling code here:
        graphOps.performExportGraph();
    }//GEN-LAST:event_performExportGraph

    private void performDeleteGraph(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performDeleteGraph
        // TODO add your handling code here:
        String selectedGraphName = graphList.getSelectedValue();
        Graph selectedGraph = graphManager.getGraph(selectedGraphName);

        if (selectedGraph != null) {
            graphManager.removeGraph(selectedGraphName);
            updateGraphListUI();
        } else {
            JOptionPane.showMessageDialog(null, "No graph selected.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_performDeleteGraph
    // Static method to add graph and update UI
    public static void addGraphToManager(Graph graph) {
        graphManager.addGraph(graph);
        SwingUtilities.invokeLater(() -> {
            if (JFrame.getFrames().length > 0 && JFrame.getFrames()[0] instanceof MainFrame) {
                ((MainFrame) JFrame.getFrames()[0]).updateGraphListUI();
            }
        });
    }

    private void performCreateGraph(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performCreateGraph
        SwingUtilities.invokeLater(() -> {
            GraphCreationFrame frame = new GraphCreationFrame();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setVisible(true);
        });
    }//GEN-LAST:event_performCreateGraph

    private void performShowAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performShowAbout
        // TODO add your handling code here:

        // Display about information in a JOptionPane dialog
        String aboutText = """
                       University of Upper-Alsace
                       Project: Graph Algorithms 2024
                       Made by: AIT OUBELLI, ROUAMI""";

    JOptionPane.showMessageDialog(null, aboutText, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_performShowAbout

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutButton;
    private javax.swing.JButton adjMatrixButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton createGraphButton;
    private javax.swing.JMenuItem danzigAlg;
    private javax.swing.JButton ddeButton;
    private javax.swing.JButton ddiButton;
    private javax.swing.JButton deleteGraphButton;
    private javax.swing.JMenuItem dijkstraAlg;
    private javax.swing.JMenuItem distanceAlg;
    private javax.swing.JButton exportGraphButton;
    private javax.swing.JButton fpAppButton;
    private javax.swing.JButton fsApsButton;
    private javax.swing.JLabel graphCount;
    private javax.swing.JList<String> graphList;
    private javax.swing.JLabel graphTypeLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem kruskalAlg;
    private javax.swing.JLabel numberOfEdgesLabel;
    private javax.swing.JLabel numberOfVerticesLabel;
    private javax.swing.JMenuItem pruferAlg;
    private javax.swing.JMenuItem rankAlg;
    private javax.swing.JMenuItem scheduleManagerAlg;
    private javax.swing.JMenuItem tarjanAlg;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JButton weightMatButton;
    // End of variables declaration//GEN-END:variables
}
